language: node_js
node_js:
  - 13

services:
  - docker

# pre install testing
install: 
  - echo "nothing need to be installed"

# scripts to be run such as test
before_script: 
  - echo "no tests"

script: 
  - docker --version # print the version for logging
  - docker build -t simple-node .
  - docker tag simple-node alvin254/simple-node:latest


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push YOUR_DOCKER_HUB/simple-node